version=${project.version}

launcherShortname=Tahan Launcher
offlinePlayerName=Player

versionManifestUrl=https://launchermeta.mojang.com/mc/game/version_manifest.json
librariesSource=https://libraries.minecraft.net/
assetsSource=https://resources.download.minecraft.net/
yggdrasilAuthUrl=https://authserver.mojang.com/authenticate
microsoftClientId=d18bb4d8-a27f-4451-a87f-fe6de4436813
resetPasswordUrl=https://minecraft.net/resetpassword

newsUrl=https://example.fr/index.html?version=%s
packageListUrl=https://example.fr/packages.json?key=%s
selfUpdateUrl=https://example.fr/launcher/latest.json
