#
# SK's Minecraft Launcher
# Copyright (C) 2010-2014 Albert Pham <http://www.sk89q.com> and contributors
# Please see LICENSE.txt for license information.
#

errorTitle=Une erreur est survenue
confirmTitle=Continuer

context.cut=Couper
context.copy=Copier
context.paste=Coller
context.delete=Supprimer
context.selectAll=Tout s\u00e9lectionner

errors.openUrlError=Impossible d'ouvir l'URL\: {0}
errors.openDirError=Impossible d'ouvrir ''{0}''. Peut-\u00EAtre qu'il n'existe pas?
errors.reportErrorPreface=Pour signaler cette erreur, veuillez fournir\:\n\n
errors.genericError=Une erreur est survenue.
errors.updateRequiredError=Veuillez t\u00e9l\u00e9charger la derni\u00e8re version du launcher pour continuer la mise \u00E0 jour..
errors.selfUpdateCheckError=La v\u00e9rification des mises \u00E0 jour du launcher a \u00e9chou\u00e9...

button.cancel=Annuler
button.ok=Continuer
button.save=Sauvegarder
button.launchAnyway=Lancer quand m\u00EAme

options.title = Options
options.useProxyCheck = Utiliser le proxy suivant dans minecraft
options.jvmPath=Version Java de secours\:
options.jvmRuntime=Version Java\:
options.jvmArguments=Arguments JVM\:
options.64BitJavaWarning=<html>Assurez-vous d'avoir install\u00e9 <strong>Java 64 bits</strong> si vous pr\u00e9voyez d'augmenter les limites de m\u00e9moire.
options.minMemory=M\u00e9moire minimum (MB)\:
options.maxMemory=M\u00e9moire maximum (MB)\:
options.permGen=PermGen (MB)\:
options.javaTab=Java
options.windowWidth=Largeur de la fen\u00EAtre\:
options.windowHeight=Hauteur de la fen\u00EAtre\:
options.enableConsoleCheck= Ouvre la console au lancement du jeu
options.minecraftTab=Minecraft
options.proxyHost=Proxy host\:
options.proxyPort=Proxy port\:
options.proxyUsername=Proxy username\:
options.proxyPassword=Proxy password\:
options.proxyTab=Proxy
options.gameKey=Arguments personnalis\u00e9s\:
options.advancedTab=Avanc\u00e9
options.about=\u00C0 propos
options.launcherConsole=Console
options.launcherAccounts=Comptes

instance.launch=Lancer
instance.install=Installer
instance.openFolder=Ouvrir le dossier
instance.openSaves=Ouvrir les maps
instance.openResourcePacks=Ouvrir les packs de ressources
instance.openScreenshots=Ouvrir les screenshots
instance.copyAsPath=Copier en tant que chemin d'acc\u00e8s
instance.openSettings=Param\u00e8tres...
instance.forceUpdate=Forcer la mise \u00E0 jour
instance.hardForceUpdate=Forcer la mise \u00E0 jour mais + violent...
instance.deleteFiles=Supprimer les fichiers...
instance.confirmDelete=\u00CAtes-vous sûr de vouloir supprimer TOUS LES FICHIERS (captures d'\u00e9cran, mondes, configs) pour ''{0}''?
instance.deletingTitle=Suppression de l'instance...
instance.deletingStatus=Suppression de ''{0}'' et ses fichiers...
instance.confirmHardUpdate=Une mise \u00E0 jour forc\u00e9e supprimera le contenu des dossiers config/ et mods/ et n\u00e9cessitera ensuite une nouvelle mise \u00E0 jour. \u00CAtes-vous sûr de vouloir continuer ?
instance.resettingTitle=R\u00e9initialisation de l'instance...
instance.resettingStatus=R\u00e9initialisation de ''{0}''...

instance.options.title=Param\u00e8tres de l'instance
instance.options.customJava=Utiliser une version de Java personnalis\u00e9e
instance.options.customMemory=Utiliser les param\u00e8tres de m\u00e9moire personnalis\u00e9s

launcher.launch=Jouer...
launcher.checkForUpdates=V\u00e9rification des mises \u00E0 jours
launcher.options=Param\u00e8tres...
launcher.updateLauncher=Mise \u00E0 jour du launcher...
launcher.downloadUpdates=Mettre \u00E0 jour les modpacks
launcher.title=Tahan Launcher
launcher.appTitle=Tahan Launcher
launcher.refreshList=Refresh la liste
launcher.checkingTitle=R\u00e9cup\u00e9ration des modpacks disponibles...
launcher.checkingStatus=R\u00e9cup\u00e9ration des modpacks disponibles... Veuillez patienter.
launcher.selfUpdatingTitle=Mise \u00E0 jour du launcher...
launcher.selfUpdatingStatus=Installation de la mise \u00E0 jour du launcher...
launcher.selfUpdateComplete=Red\u00e9marrez le launcher pour utiliser la nouvelle version..
launcher.selfUpdateCompleteTitle=Mise \u00E0 jour termin\u00e9e
launcher.updatingTitle=Mise \u00E0 jour...
launcher.updatingStatus=Mise \u00E0 jour de ''{0}''... Veuillez patienter.
launcher.noInstanceError=Veuillez s\u00e9lectionner un modpack \u00E0 lancer.
launcher.noInstanceTitle=Aucun modpack s\u00e9lectionn\u00e9
launcher.launchingTItle=Lancement du jeu...
launcher.launchingStatus=Lancement de ''{0}''. Veuillez patienter.
launcher.javaMismatchTitle=Erreur avec la version Java actuelle.
launcher.modpackColumn=Modpack
launcher.notInstalledHint=(non install\u00e9)
launcher.requiresUpdateHint=(a besoin de mise \u00E0 jour)
launcher.updatePendingHint=(mise \u00E0 jour en attente)

accounts.title=S\u00e9lectionnez le compte \u00E0 utiliser (pr\u00e9f\u00e9rez les comptes hors-ligne)
accounts.play=Utiliser
accounts.refreshingStatus=Refresh de la session...
accounts.addMojang=Ajouter un compte Mojang (pass\u00e9)

accounts.addMicrosoft=Ajouter un compte Microsoft
accounts.addCrack=Ajouter un compte crack
accounts.removeSelected=Supprimer ce compte
accounts.confirmForgetTitle=Supprimer le compte
accounts.confirmForget=\u00CAtes vous sûr de vouloir supprimer ce compte du launcher?

login.login=Connexion...
login.recoverAccount=Mot de passe oubli\u00e9 ?
login.playOffline=Jouer en mode hors-ligne (pass\u00e9)
login.title=Connexion Minecraft
login.defaultMessage=Connexion \u00E0 votre compte Microsoft
login.crackMessage=Entrez votre nom d'utilisateur
login.username=Nom d'utilisateur\:
login.idEmail=Email\:
login.password=Mot de passe\:
login.noPasswordError=Veuillez rentrer un mot de passe.
login.noPasswordTitle=Mot de passe manquant
login.loggingInTitle=Connexion...
login.loggingInStatus=Connexion \u00E0 minecraft...
login.noLoginError=Veuillez entrer les information de votre compte.
login.noLoginTitle=Il vous manque un compte
login.minecraftNotOwnedError=D\u00e9sol\u00e9, Minecraft n'est pas achet\u00e9 sur ce compte.
login.relogin=Veuillez vous reconnecter. ({0})

login.microsoft.seeBrowser=V\u00e9rifiez votre navigateur pour vous connecter avec Microsoft.
login.xbox.generic=\u00c9chec de l'authentification aupr\u00e8s de Xbox Live.
login.xbox.noXboxAccount=Ce compte n'est associ\u00e9 \u00E0 aucun compte Xbox !
login.xbox.isChild=Le compte est celui d'un enfant (moins de 18 ans) et ne peut \u00EAtre trait\u00e9 que s'il fait partie d'une famille.
login.xbox.unknown=Une erreur inconnue s'est produite lors de la connexion avec Xbox (XErr {0})
connexion.xbox.errorMessage=Une erreur inconnue s'est produite lors de la connexion avec Xbox : {0}
login.minecraft.error=Une erreur s'est produite lors de l'autorisation aupr\u00e8s des services Minecraft : {0}

console.title=Messages et Erreurs
console.launcherConsoleTitle=Console
console.uploadLog=Refresh les logs
console.pasteUploading=Envoi de {0} bytes...\n
console.pasteUploaded=Paste envoy\u00e9\: {0}\n
console.pasteFailed=\u00c9chec de l'envoi\: {0}\n
console.processEndCode=Le processus s'est termin\u00e9 avec l'erreur\: {0}
console.attachedToProcess=Le jeu est encore en cours d'\u00e9xecution, veuillez patienter.
console.forceClose=Forcer la fermeture
console.trayTooltip=Tahan Launcher
console.trayTitle=Tahan Launcher
console.tray.showWindow=Afficher la fen\u00EAtre
console.tray.forceClose=Force close...
console.closeWindow=Fermer la fen\u00EAtre
console.hideWindow=Cacher la fen\u00EAtre
console.confirmKill=\u00CAtes-vous sûr de vouloir forcer la fermeture? Vous pourriez perdre des donn\u00e9es.
console.confirmKillTitle=\u00CAtes-vous sûr?
console.clearLog=Effacer

downloader.downloadingItem=T\u00e9l\u00e9chargement {0}...
downloader.downloadingList=T\u00e9l\u00e9chargement de {0} fichiers... ({1} restants, {2} failed)
downloader.jobProgress={1,number}%\t{0}
downloader.jobPending=...\t{0}
downloader.noDownloads=Pas de t\u00e9l\u00e9chargements en attente.
downloader.failedCount=({0} have failed)

progress.details=D\u00e9tails...
progress.less=Voir moins...
progress.viewLog=Voir les logs
progress.confirmCancel=\u00CAtes-vous sûr de vouloir annuler?
progress.confirmCancelTitle=Annuler
progress.defaultStatus=Travail...
progress.percentTitle=({0}%) {1}

installer.installing=Installation...
installer.executing=\u00c9xecution des tâches... ({0} restantes)
installer.copyingFile=Copie de {0} \u00E0 {1}
installer.movingFile=D\u00e9placement de {0} \u00E0 {1}
installer.runningProcessor=\u00c9xecution du processeur {0}: {1}

updater.updating=Mise \u00E0 jour du launcher...
updater.updateRequiredButOffline=Une mise \u00E0 jour est n\u00e9cessaire, mais vous devez \u00EAtre en ligne.
updater.updateRequiredButNoManifest=Une mise \u00E0 jour est n\u00e9cessaire, mais les informations de mise \u00E0 jour pour cette instance ne sont plus disponibles.

instanceUpdater.preparingUpdate=Pr\u00e9paration de la mise \u00E0 jour...
instanceUpdater.readingManifest=Lecture du manifest du package...
instanceUpdater.readingVersion=Lecture du manifest de la version...
instanceUpdater.buildingDownloadList=Collecte des fichiers \u00E0 t\u00e9l\u00e9charger...
instanceUpdater.collectingLibraries=Collecte de biblioth\u00e8ques \u00E0 t\u00e9l\u00e9charger...
instanceUpdater.collectingAssets=Collecte des ressources \u00E0 t\u00e9l\u00e9charger...

instanceDeleter.deleting=Suppression de {0}...
instanceDeleter.failures=Impossible de supprimer {0} fichier(s).

instanceResetter.resetting=R\u00e9initialisation de {0}...
instanceLoader.loadingLocal=Chargement des instances locales depuis le disque...
instanceLoader.checkingRemote=Recherche de nouveaux packs de mods...

runner.preparing=Pr\u00e9paration du lancement...
runner.collectingArgs=Collecte des arguments du processus...
runner.startingJava=D\u00e9marrage de Java...
runner.updateRequired=Cette instance doit \u00EAtre mise \u00E0 jour avant de pouvoir \u00EAtre ex\u00e9cut\u00e9e.
runner.missingLibrary={0} doit \u00EAtre relanc\u00e9 et mis \u00E0 jour car la biblioth\u00e8que ''{1}'' est manquante.
runner.missingAssetsIndex={0} doit \u00EAtre relanc\u00e9 et mis \u00E0 jour car son index d'actifs est manquant.
runner.corruptAssetsIndex={0} doit \u00EAtre relanc\u00e9 et mis \u00E0 jour car son index d'actifs est corrompu.
runner.wrongJavaVersion=L'instance ''{0}'' requiert la version Java {1}, mais n'a pu trouver que {2}.

assets.expanding1=D\u00e9veloppement de l'actif {0}... ({1} restant)
assets.expandingN=D\u00e9veloppement des actifs {0}... ({1} restants))
assets.missingIndex=Vous devez mettre \u00E0 jour cette instance car son fichier d'index \u00E0 l'emplacement ''{0}'' est manquant.
assets.missingObject=Vous devez mettre \u00E0 jour cette instance car le fichier \u00E0 l'emplacement ''{0}'' est manquant.

features.nameColumn=Fonctionnalit\u00e9
features.title=S\u00e9lectionnez les fonctionnalit\u00e9s
features.install=Continuer
features.selectForInfo=S\u00e9lectionnez une fonctionnalit\u00e9 pour afficher plus d'informations.
features.intro=Veuillez s\u00e9lectionner les fonctionnalit\u00e9s optionnelles \u00E0 installer.
features.starred=(recommand\u00e9)
features.avoid=(d\u00e9recommand\u00e9)